# Generated by Django 4.1.1 on 2022-09-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('user_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['birth_date', 'first_name', 'last_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name', 'description']},
        ),
    ]
