# Generated by Django 4.1.1 on 2022-09-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name', 'description']},
        ),
    ]
